Add context.error(statusCode) function
catberry/catberry pull request #337
Opened 2017-04-12 10:43 UTC by reenko

Add context.error(statusCode) function for proxy errors code from API.
For example, if API returned 500 HTTP status code than return 500 page.

2017-04-18 15:08 UTC, rdner requested changes

2017-04-18 15:08 UTC, pragmader commented on lib/providers/ModuleApiProvider.js
> +			errorStatusCode: null,
Also, would be nice to make `notFound` an alias for `error(404)` and `redirect` to set `statusCode: 3xx`

2017-04-23 11:28 UTC, rdner requested changes
I will work on this branch later, it requires some additional changes.

2017-04-23 11:28 UTC, pragmader commented on lib/providers/ModuleApiProvider.js
> +			errorStatusCode: 200,
I meant to name it `statusCode` and use it always writing the headers. Also, implement the redirect using this status code as well.

2017-10-01 19:30 UTC, closed without merging